### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by pingu1m** [vhbelvadi/LaTeX-lecture-notes-class#1]
Hi would you know why I'm getting this error?

$HOME/texmf/tex/latex/lecture-notes-class/lecture.cls:147: Undefined co
ntrol sequence.
\ds@english ...notes@lang }{english} \dateenglish 
                                                  \newcommand {\notes@lectur...
l.147

**Comment by vhbelvadi** [comment]
Thanks for reporting this. I'll look it up.

**Comment by vhbelvadi** [comment]
Have you possibly forgotten to provide options in `documentclass`?

Using just `\documentclass{lecture}` throws this error which is understandable since the language and type haven't been mentioned (these must compulsorily be specified—see [readme](https://github.com/vhbelvadi/LaTeX-lecture-notes-class/blob/master/README.md)). Specifying at least these two options e.g. `\documentclass[english, seminar]{lecture}` should work fine.

If you still see this error despite this, please let me know and we can investigate further.

**Comment by vhbelvadi** [comment]
Closing this issue as this bug has been fixed in v2.3.1.
Thanks for reporting @pingu1m.
